version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: nginx
    volumes:
      - ./public-data:/app/public
      - ./tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
